#!/usr/bin/env python3
"""Insert the CMU reader section and its full Appendix B theorem record."""

from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
BOOK = ROOT / "notes" / "Microeconomics_1_notes_by_Victor_Aguiar.lyx"
STAMP = "ECON803_CMU_SECTION:1"
APPENDIX_STAMP = "ECON803_CMU_APPENDIX:1"


def marker(text: str) -> str:
    return f"""\\begin_layout Standard
\\begin_inset Note Note
status collapsed

\\begin_layout Plain Layout
{text}
\\end_layout

\\end_inset


\\end_layout

"""


MAIN = r'''\begin_layout Section
WGARP and Coalitional Multi-Utility
\end_layout

\begin_layout Standard
Afriat's theorem asks whether all observations can be generated by maximization of one utility function.
 Its answer is GARP.
 A failure of GARP rejects that joint transitive explanation, but it need not make every pair of observations inconsistent.
 WGARP asks the weaker pairwise question: can the data avoid every strict two-observation reversal even when a longer revealed-preference cycle remains?
 Coalitional multi-utility (CMU) is the optimizing model behind that condition
\begin_inset CommandInset citation
LatexCommand citep
key "aguiarhjertstrandserranoevren2026"
literal "false"

\end_inset
.
 Crucially, CMU extends the benchmark model: ordinary utility maximization is exactly its singleton special case.
\end_layout

\begin_layout Definition
Budget WGARP and WARP.
 The finite dataset \begin_inset Formula $\mathcal O$\end_inset
 satisfies WGARP if, for all \begin_inset Formula $s,t\in\mathbb T$\end_inset
,
\begin_inset Formula
\[
p^t\cdot x^t\geq p^t\cdot x^s
\quad\Longrightarrow\quad
\neg\bigl(p^s\cdot x^s>p^s\cdot x^t\bigr).
\]
\end_inset
It satisfies WARP if, whenever \begin_inset Formula $x^t\neq x^s$\end_inset
,
\begin_inset Formula
\[
p^t\cdot x^t\geq p^t\cdot x^s
\quad\Longrightarrow\quad
p^s\cdot x^s<p^s\cdot x^t.
\]
\end_inset
WGARP is the weak/strict condition appropriate for a demand correspondence.
 WARP also excludes mutual affordability at equality and corresponds to a strict, single-valued version of the model.
 GARP and SARP apply the analogous prohibitions after taking revealed-preference closure.
\end_layout

\begin_layout Definition
Preference-function demand.
 A \begin_inset Formula $\notationfirst{preference-function}{r:X\times X\to\mathbb R}$\end_inset
 is a numerical comparison rule, with \begin_inset Formula $x\succeq_r y$\end_inset
 when \begin_inset Formula $r(x,y)\geq0$\end_inset
.
 Its demand correspondence is
\begin_inset Formula
\[
\notationfirst{preference-demand}{x_r(p,w)}
=\{x\in B(p,w):r(x,y)\geq0\text{ for every }y\in B(p,w)\}.
\]
\end_inset
The function is asymmetric when \begin_inset Formula $r(x,y)\geq0\Rightarrow r(y,x)\leq0$\end_inset
 and \begin_inset Formula $r(x,y)>0\Rightarrow r(y,x)<0$\end_inset
.
 It is strictly increasing when \begin_inset Formula $x>z\Rightarrow r(x,y)>r(z,y)$\end_inset
 for every \begin_inset Formula $y$\end_inset
.
 The strict part of \begin_inset Formula $\succeq_r$\end_inset
 remains the relational strict part; it is not defined merely by \begin_inset Formula $r(x,y)>0$\end_inset
.
\end_layout

\begin_layout Definition
Coherent CMU.
 Let \begin_inset Formula $C(X)$\end_inset
 be the continuous real-valued functions on \begin_inset Formula $X$\end_inset
 with the compact-open topology.
 A compact coalition structure \begin_inset Formula $\notationfirst{cmu-coalition-structure}{\Omega}$\end_inset
 is a nonempty compact collection of nonempty compact sets \begin_inset Formula $\notationfirst{cmu-coalition}{U\subseteq C(X)}$\end_inset
.
 Its preference function is
\begin_inset Formula
\[
\notationfirst{cmu-preference-function}{r_\Omega(x,y)}
=\max_{U\in\Omega}\min_{u\in U}\bigl[u(x)-u(y)\bigr].
\]
\end_inset
The structure is coherent if \begin_inset Formula $U\cap V\neq\varnothing$\end_inset
 for every \begin_inset Formula $U,V\in\Omega$\end_inset
.
 Coherence is pairwise intersection; it does not require one utility to belong to every coalition.
 A CMU comparison holds when at least one coalition unanimously ranks the first bundle at least as high as the second.
\end_layout

\begin_layout Proposition
Classical utility maximization is nested exactly.
 Let \begin_inset Formula $u\in C(X)$\end_inset
 and set \begin_inset Formula $\Omega_u=\{\{u\}\}$\end_inset
.
 Then \begin_inset Formula $\Omega_u$\end_inset
 is compact and coherent,
 \begin_inset Formula $r_{\Omega_u}(x,y)=u(x)-u(y)$\end_inset
, and
\begin_inset Formula
\[
x_{r_{\Omega_u}}(p,w)=\arg\max_{x\in B(p,w)}u(x).
\]
\end_inset
\begin_inset CommandInset label
LatexCommand label
name "prop:cmu-singleton"

\end_inset
\end_layout

\begin_layout Proof
Both optimization operators in the CMU formula collapse for the singleton coalition, so \begin_inset Formula $r_{\Omega_u}(x,y)=u(x)-u(y)$\end_inset
.
 Therefore \begin_inset Formula $x\in x_{r_{\Omega_u}}(p,w)$\end_inset
 exactly when \begin_inset Formula $u(x)\geq u(y)$\end_inset
 for every feasible \begin_inset Formula $y$\end_inset
, which is the ordinary utility-maximization condition.
 A singleton is compact and intersects itself.
\end_layout

\begin_layout Theorem
Reader theorem \begin_inset Formula $(\star)$\end_inset
: WGARP and coherent CMU.
 For a finite expenditure-exhausting dataset with \begin_inset Formula $L\geq2$\end_inset
, strictly positive prices, and nonzero nonnegative choices, the following are equivalent: (i) WGARP; (ii) rationalization by an asymmetric, strictly increasing, continuous preference function; (iii) rationalization by a coherent, strictly increasing, continuous CMU; and (iv) rationalization by a skew-symmetric, coherent, continuous CMU whose coalitions contain strictly increasing concave utilities.
\begin_inset CommandInset label
LatexCommand label
name "thmstar:wgarp-cmu"

\end_inset
\end_layout

\begin_layout Standard
This is an exact finite-data characterization, not only a necessary condition.
 The difficult direction uses the fact that every two-observation subdataset of a WGARP dataset satisfies GARP, constructs a pairwise Afriat utility for each pair, and assembles those utilities into a coherent coalition structure.
 Passing WGARP does not identify nontransitivity: every GARP dataset also passes WGARP and can admit both classical and CMU rationalizations.
\end_layout

\begin_layout Theorem
Reader theorem \begin_inset Formula $(\star)$\end_inset
: WARP and strict coherent CMU.
 In the same finite environment, WARP is equivalent to rationalization by an asymmetric, strictly star-concave, continuous preference function; equivalently, by a coherent strictly star-concave CMU; equivalently, by a skew-symmetric coherent CMU whose coalitions contain strictly increasing strictly concave utilities.
 Here strict star-concavity requires
 \begin_inset Formula $r(\alpha x+(1-\alpha)y,x)>\alpha r(x,x)+(1-\alpha)r(y,x)$\end_inset
 for \begin_inset Formula $x\neq y$\end_inset
 and \begin_inset Formula $\alpha\in(0,1)$\end_inset
.
\begin_inset CommandInset label
LatexCommand label
name "thmstar:warp-cmu"

\end_inset
\end_layout

\begin_layout Standard
The WARP theorem is separate from the WGARP theorem.
 WARP is not the finite-data condition for maximization of one ordinary utility function: GARP is the classical weak-rationalizability condition, and SARP is the corresponding strict acyclicity condition.
 The strict CMU theorem yields at most one demanded bundle on a budget when demand is nonempty, but it does not guarantee nonempty demand on every counterfactual budget.
\end_layout

\begin_layout Example
A three-good WGARP dataset that violates GARP.
 Let
\begin_inset Formula
\[
\begin{array}{lll}
p^1=(4,1,5),&p^2=(5,4,1),&p^3=(1,5,4),\\
x^1=(4,1,1),&x^2=(1,4,1),&x^3=(1,1,4).
\end{array}
\]
\end_inset
Then
\begin_inset Formula
\[
[p^t\cdot x^s]_{t,s=1}^3=
\begin{pmatrix}22&13&25\\25&22&13\\13&25&22\end{pmatrix}.
\]
\end_inset
Hence \begin_inset Formula $x^1\succ^{R,D}x^2\succ^{R,D}x^3\succ^{R,D}x^1$\end_inset
, so GARP fails.
 Each reverse-budget cost is \begin_inset Formula $25>22$\end_inset
, however, so no pair creates a WGARP reversal.
 This dataset also satisfies WARP because the chosen bundles are distinct and no pair is mutually affordable.
 With two goods, WGARP and GARP coincide; three goods are essential for this separation under linear budgets.
\end_layout

\begin_layout Proposition
Compensated law of demand for preference functions.
 Let \begin_inset Formula $r$\end_inset
 be asymmetric and strictly increasing, let \begin_inset Formula $x\in x_r(p,w)$\end_inset
, and set \begin_inset Formula $w'=p'\cdot x$\end_inset
.
 If \begin_inset Formula $x'\in x_r(p',w')$\end_inset
, then
\begin_inset Formula
\[
(p'-p)\cdot(x'-x)\leq0.
\]
\end_inset
\begin_inset CommandInset label
LatexCommand label
name "prop:cmu-cld"

\end_inset
\end_layout

\begin_layout Proof
Strict increase and asymmetry imply budget exhaustion at every nonempty demand.
 Thus \begin_inset Formula $p'\cdot(x'-x)=0$\end_inset
.
 At the new budget, the old choice \begin_inset Formula $x$\end_inset
 is affordable at equality.
 WGARP therefore rules out \begin_inset Formula $p\cdot x>p\cdot x'$\end_inset
, so \begin_inset Formula $p\cdot(x'-x)\geq0$\end_inset
.
 Subtracting the two expressions gives the result.
 The claim is conditional on both demand sets being nonempty.
\end_layout

\begin_layout Remark
What survives, and what does not.
 Singleton CMU reproduces the UMP exactly.
 Under asymmetry and strict increase, nonempty CMU demand satisfies budget exhaustion, homogeneity of degree zero, WGARP, and the compensated inequality above.
 WGARP or coherence alone does not imply one scalar utility, transitivity, GARP, convex preferences, nonempty counterfactual demand, Roy's identity, Shephard's lemma, Slutsky symmetry, or the standard scalar-utility welfare measures.
 Concavity of the component utilities does not make the induced CMU relation globally convex.
 An arbitrary noncoherent CMU need not satisfy WGARP.
\end_layout

\begin_layout Standard
The star marks a compressed reader theorem, not a weaker truth standard and not a Lean-verification badge.
 The six-way WGARP statement, the distinct WARP theorem, topology, proof boundary, and formalization record appear in Appendix 
\begin_inset CommandInset ref
LatexCommand ref
reference "app:cmu-technical"
nolink "false"

\end_inset
.
\end_layout

'''


APPENDIX = r'''\begin_layout Chapter
Technical Theorem Records
\end_layout

\begin_layout Standard
\begin_inset CommandInset label
LatexCommand label
name "app:cmu-technical"

\end_inset
\end_layout

\begin_layout Standard
A starred theorem in the main text is a reader-level statement.
 This appendix records its exact environment, full equivalences, proof boundary, and formal-verification status.
 The star never means that omitted assumptions may be guessed and never means that a theorem is Lean verified.
\end_layout

\begin_layout Section
WGARP and Coherent CMU
\end_layout

\begin_layout Standard
Result ID: CT-RP-WGARP-CMU.
 Let \begin_inset Formula $L\geq2$\end_inset
, \begin_inset Formula $X=\mathbb R_+^L$\end_inset
, and \begin_inset Formula $\mathcal O=\{(p^t,x^t)\}_{t\in\mathbb T}$\end_inset
 be finite, with \begin_inset Formula $p^t\in\mathbb R_{++}^L$\end_inset
, \begin_inset Formula $x^t\in X\setminus\{0\}$\end_inset
, and observed wealth \begin_inset Formula $w^t=p^t\cdot x^t$\end_inset
.
 Equip \begin_inset Formula $C(X)$\end_inset
 with the topology of uniform convergence on compact subsets.
 A compact coalition structure is a compact collection \begin_inset Formula $\Omega$\end_inset
 of nonempty compact subsets of \begin_inset Formula $C(X)$\end_inset
, under the induced Hausdorff topology.
\end_layout

\begin_layout Theorem
Full WGARP--CMU characterization.
 Under the preceding displayed environment, the following six statements are equivalent.
\begin_inset CommandInset label
LatexCommand label
name "thmfull:wgarp-cmu"

\end_inset
\end_layout

\begin_layout Enumerate
The data are rationalized by an asymmetric, strictly increasing, continuous preference function \begin_inset Formula $r:X\times X\to\mathbb R$\end_inset
.
\end_layout

\begin_layout Enumerate
The data are rationalized by a coherent, strictly increasing, continuous CMU function.
\end_layout

\begin_layout Enumerate
The data are rationalized by a skew-symmetric, coherent, continuous CMU function whose coalitions consist of strictly increasing concave utilities.
\end_layout

\begin_layout Enumerate
The data satisfy WGARP.
\end_layout

\begin_layout Enumerate
For every \begin_inset Formula $s,t\in\mathbb T$\end_inset
 there exist \begin_inset Formula $R^{s,t}\in\mathbb R$\end_inset
 and \begin_inset Formula $\lambda^s_{s,t},\lambda^t_{s,t}>0$\end_inset
 such that
\begin_inset Formula
\[
R^{s,t}=-R^{t,s},\qquad
\lambda^s_{s,t}=\lambda^s_{t,s},\qquad
R^{s,t}\geq\lambda^s_{s,t}p^s\cdot(x^s-x^t).
\]
\end_inset
\end_layout

\begin_layout Enumerate
There are antisymmetric numbers \begin_inset Formula $V^{s,t}=-V^{t,s}$\end_inset
 such that
\begin_inset Formula
\[
\begin{aligned}
p^s\cdot(x^s-x^t)\geq0&\Longrightarrow V^{s,t}\geq0,\\
p^s\cdot(x^s-x^t)>0&\Longrightarrow V^{s,t}>0
\end{aligned}
\qquad(s,t\in\mathbb T).
\]
\end_inset
\end_layout

\begin_layout Standard
Proof record.
 The easy implications from a rationalizing preference function to WGARP and between the two numerical certificate systems are finite arguments.
 The reverse representation direction constructs symmetric pairwise Afriat utilities and assembles them into compact coherent coalitions.
 That research-level construction, including compactness and skew-symmetry, is proof-delegated to the exact finite-data theorem of
\begin_inset CommandInset citation
LatexCommand citep
key "aguiarhjertstrandserranoevren2026"
literal "false"

\end_inset
; this book does not relabel the delegation as an independent proof.
\end_layout

\begin_layout Standard
Boundary note.
 Coherence means pairwise intersection and need not imply a common utility in every coalition.
 A general coherent CMU may be incomplete or intransitive.
 The representation rationalizes the observed budgets but does not guarantee nonempty demand at all counterfactual budgets.
\end_layout

\begin_layout Section
WARP and Strict Coherent CMU
\end_layout

\begin_layout Standard
Result ID: CT-RP-WARP-CMU.
 A preference function is strictly star-concave when, for every \begin_inset Formula $x\neq y$\end_inset
 and \begin_inset Formula $\alpha\in(0,1)$\end_inset
,
\begin_inset Formula
\[
r(\alpha x+(1-\alpha)y,x)>
\alpha r(x,x)+(1-\alpha)r(y,x).
\]
\end_inset
This condition concerns the first argument along line segments ending at the second argument; it is not global concavity of the two-argument function.
\end_layout

\begin_layout Theorem
Full WARP--CMU characterization.
 In the same finite budget environment, the following are equivalent: (i) WARP; (ii) rationalization by an asymmetric, strictly star-concave, continuous preference function; (iii) rationalization by a coherent, strictly star-concave, continuous CMU; and (iv) rationalization by a skew-symmetric, coherent, continuous CMU whose coalitions consist of strictly increasing strictly concave utilities.
\begin_inset CommandInset label
LatexCommand label
name "thmfull:warp-cmu"

\end_inset
\end_layout

\begin_layout Standard
Proof record.
 The proof uses strict pairwise utility rationalizations and is separately delegated to the WARP theorem and online appendix of
\begin_inset CommandInset citation
LatexCommand citep
key "aguiarhjertstrandserranoevren2026"
literal "false"

\end_inset
.
 It is not obtained by merely replacing the acronym WGARP in the preceding theorem.
\end_layout

\begin_layout Section
Formalization Record and Boundaries
\end_layout

\begin_layout Description
CT-RP-CMU-SINGLETON.
 Textbook proof complete; local Lean target.
 The exact singleton reduction is elementary and introduces no compactness machinery beyond the singleton case.
\end_layout

\begin_layout Description
CT-RP-CMU-CLD.
 Lean core verified through the pinned WGARP project and the compiled declaration \begin_inset Formula $\texttt{Econ803.Consumer.compensated\_law\_of\_demand}$\end_inset
.
 The certificate covers the asymmetric, strictly increasing preference-function result stated in the chapter.
\end_layout

\begin_layout Description
CT-RP-WGARP-CMU and CT-RP-WARP-CMU.
 Cited theorems, not yet Lean complete.
 A complete formalization requires the pairwise Afriat construction, compact-open and Hausdorff topology, coherence, and the strict-rationalization dependencies.
\end_layout

\begin_layout Standard
The model does not by itself recover transitivity, global convexity, classical UMP--EMP duality, Slutsky symmetry, scalar-utility welfare comparisons, or global existence of counterfactual demand.
 Those conclusions remain owned by the benchmark chapters and require their displayed assumptions.
\end_layout

'''


def rewrite(text: str) -> str:
    if STAMP in text or APPENDIX_STAMP in text:
        if STAMP in text and APPENDIX_STAMP in text:
            return text
        raise ValueError("partial CMU insertion detected")

    next_source_marker = (
        "ECON803_CONSUMER_RESTRUCTURE_SOURCE:section:"
        "consumer-theory-utility-maximization:18:revealed-preference-and-the-strong-axiom"
    )
    marker_at = text.index(next_source_marker)
    insert_at = text.rfind("\\begin_layout Standard\n", 0, marker_at)
    if insert_at < 0:
        raise ValueError("cannot locate the SARP provenance layout")
    text = text[:insert_at] + marker(STAMP) + MAIN + text[insert_at:]

    glossary = "\\begin_layout Chapter\nGlossary of Symbols\n\\end_layout"
    if text.count(glossary) != 1:
        raise ValueError("cannot uniquely locate the glossary appendix")
    text = text.replace(glossary, marker(APPENDIX_STAMP) + APPENDIX + glossary, 1)
    return text


def main() -> None:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--apply", action="store_true")
    args = parser.parse_args()
    source = BOOK.read_text()
    revised = rewrite(source)
    if args.check:
        if revised != source:
            raise SystemExit("CMU theorem insertion is pending")
        print("CMU theorem section and appendix are present")
    elif revised != source:
        BOOK.write_text(revised)
        print(f"updated {BOOK}")
    else:
        print("no changes needed")


if __name__ == "__main__":
    main()
