#!/usr/bin/env python3
"""Repair the narrative contract of the reorganized consumer block.

This pass is intentionally textual: it leaves theorem proofs and generated
problem blocks untouched while fixing stale roadmaps, vague headings, and the
vacuous inclusion notion of abstract weak rationalization.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
BOOK = ROOT / "notes" / "Microeconomics_1_notes_by_Victor_Aguiar.lyx"
STAMP = "ECON803_CONSUMER_NARRATIVE_POLISH:1"


def marker_note(text: str) -> str:
    return f"""\\begin_layout Standard
\\begin_inset Note Note
status collapsed

\\begin_layout Plain Layout
{text}
\\end_layout

\\end_inset


\\end_layout

"""


def standard(text: str) -> str:
    return f"\\begin_layout Standard\n{text}\n\\end_layout\n\n"


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise ValueError(f"{label}: expected one match, found {count}")
    return text.replace(old, new, 1)


def layout_end(text: str, start: int) -> int:
    token_re = re.compile(r"\\begin_layout\b|\\end_layout\b")
    depth = 0
    for match in token_re.finditer(text, start):
        if match.group(0) == "\\begin_layout":
            depth += 1
        else:
            depth -= 1
            if depth == 0:
                newline = text.find("\n", match.end())
                return len(text) if newline < 0 else newline + 1
    raise ValueError("unterminated LyX layout")


def replace_layout_starting(text: str, prefix: str, replacement: str) -> str:
    count = text.count(prefix)
    if count != 1:
        raise ValueError(f"layout prefix {prefix!r}: expected one match, found {count}")
    start = text.index(prefix)
    end = layout_end(text, start)
    return text[:start] + replacement + text[end:]


def replace_section_lead(
    text: str, heading: str, next_token: str, replacement: str
) -> str:
    section = f"\\begin_layout Section\n{heading}\n\\end_layout"
    start = text.index(section) + len(section)
    end = text.index(next_token, start)
    return text[:start] + "\n\n" + replacement.rstrip() + "\n\n" + text[end:]


CH1_OVERVIEW_OLD = (
    "This chapter derives demand from preference maximization and develops the "
    "duality between utility maximization and expenditure minimization."
)
CH1_OVERVIEW_NEW = (
    "The benchmark consumer chooses a feasible bundle to maximize a utility "
    "function.  This chapter states that model, proves existence of demand, and "
    "develops its first-order characterization.  Duality and welfare are treated "
    "in the next chapter."
)

CH1_LEAD = r'''\begin_layout Standard
The benchmark model has three primitives: a consumption set \begin_inset Formula $X$\end_inset
, a utility function \begin_inset Formula $u:X\to\mathbb{R}$\end_inset
, and a feasible-set correspondence \begin_inset Formula $(p,w)\mapsto B(p,w)$\end_inset
.
 At prices and wealth \begin_inset Formula $(p,w)$\end_inset
, the consumer solves
\begin_inset Formula
\[
x(p,w)\in\arg\max_{x\in B(p,w)}u(x).
\]
\end_inset
Everything in the chapter follows from this optimization problem plus assumptions that are displayed where they are used.
\end_layout

\begin_layout Standard
Utility is ordinal in the deterministic benchmark: if \begin_inset Formula $\phi$\end_inset
 is strictly increasing on \begin_inset Formula $u(X)$\end_inset
, then \begin_inset Formula $u$\end_inset
 and \begin_inset Formula $\phi\circ u$\end_inset
 generate exactly the same demand.
 We therefore take a utility representation as the primitive here without attaching cardinal or interpersonal meaning to its levels.
 Chapter 4 returns to the logically prior question of when an observed preference relation admits such a representation.
\end_layout'''

CH2_INTRO = r'''\begin_layout Standard
Chapter 1 tells us which bundle the benchmark consumer chooses.
 This chapter studies the same problem from its value functions.
 Indirect utility and expenditure minimization yield demand identities, comparative statics, and money-metric welfare measures.
 Set-valued duality is stated first; differentiability and uniqueness are added only for envelope formulas such as Roy's identity and Shephard's lemma.
\end_layout'''

CH3_INTRO = r'''\begin_layout Standard
The direction of analysis now reverses.
 Instead of deriving choices from \begin_inset Formula $u$\end_inset
, we ask whether observed demand could have been generated by the benchmark model and what features of that model the data recover.
 Local restrictions concern derivatives of a demand function; finite-data restrictions concern revealed-preference comparisons across observed budgets.
 GARP characterizes classical utility maximization, while WGARP admits the broader coalitional multi-utility model introduced after Afriat's theorem.
\end_layout'''

CH4_INTRO_OLD = """Choice data,
 preference relations,
 and utility representations are three descriptions of the same decision problem.
 This chapter fixes the logical relations among them before prices and wealth are introduced in the consumer-theory chapter."""

CH4_INTRO_NEW = """The preceding chapters used the geometry of linear budgets.  We now abstract from prices and wealth and retain only alternatives, feasible menus, and observed choices.  This separation shows which conclusions follow from choice consistency itself and which depend on consumer-budget structure.  It also supplies the preference and utility language that underlies the benchmark model used in Chapter 1."""

EU_INTRO = r'''\begin_layout Standard
Expected utility adds two ingredients to the choice framework: objective lotteries and a mixture operation.
 The chapter first gives the finite von Neumann--Morgenstern model and its affine uniqueness, then studies risk attitudes, stochastic dominance, portfolio choice, and revealed tests.
 Infinite lottery spaces are treated last because their topology and integrability assumptions are technical extensions rather than part of the finite core.
\end_layout'''

SC_INTRO = r'''\begin_layout Standard
Deterministic choice predicts a set of maximizers from each menu; stochastic choice records a probability distribution over that menu.
 We first define a coherent choice-probability system on a fixed finite universe, then ask when it is a mixture of deterministic rankings.
 Multinomial logit is presented afterward as a parametric special case, not as the definition of random utility.
\end_layout'''

ABSTRACT_RATIONALIZATION = r'''\begin_layout Definition
Exact rationalization.
 A binary relation \begin_inset Formula $\succeq$\end_inset
 rationalizes \begin_inset Formula $(\mathcal A,c)$\end_inset
 if
 \begin_inset Formula $c(A)=\{x\in A:x\succeq y\text{ for every }y\in A\}$\end_inset
 for every \begin_inset Formula $A\in\mathcal A$\end_inset
.
 A rational preference relation is complete and transitive.
\end_layout

\begin_layout Remark
Replacing equality by the inclusion \begin_inset Formula $c(A)\subseteq\{x\in A:x\succeq y\text{ for every }y\in A\}$\end_inset
 is only a selection-from-maximizers condition.
 By itself it has no revealed-preference content: universal indifference makes every feasible alternative greatest and therefore accommodates every nonempty choice correspondence.
 Whenever the book uses weak rationalization for budget data, it instead imposes the structural conditions stated in Afriat's theorem.
\end_layout
'''

GARP_LEAD = r'''\begin_layout Standard
Retain the expenditure-exhausting finite dataset \begin_inset Formula $\mathcal O=\{(p^t,x^t)\}_{t\in\mathbb T}$\end_inset
 and direct revealed preference \begin_inset Formula $\succeq^{R,D}$\end_inset
 from the preceding section.
 Let \begin_inset Formula $\notationfirst{revealed-closure}{\succeq^{R}}$\end_inset
 be its transitive closure on the observed bundles.
 Thus \begin_inset Formula $x^t\succeq^R x^s$\end_inset
 when there is a finite chain of direct weak comparisons from \begin_inset Formula $x^t$\end_inset
 to \begin_inset Formula $x^s$\end_inset
.
 Define \begin_inset Formula $x^t\notationfirst{strict-direct-revealed}{\succ^{R,D}}x^s$\end_inset
 when \begin_inset Formula $p^t\cdot x^t>p^t\cdot x^s$\end_inset
.
\end_layout

\begin_layout Definition
Utility rationalization of budget data.
 A utility function \begin_inset Formula $u:X\to\mathbb R$\end_inset
 rationalizes \begin_inset Formula $\mathcal O$\end_inset
 if, for every \begin_inset Formula $t\in\mathbb T$\end_inset
,
 \begin_inset Formula $u(x^t)\geq u(x)$\end_inset
 whenever \begin_inset Formula $p^t\cdot x\leq p^t\cdot x^t$\end_inset
.
 Ties are allowed, so the observed bundle need not be the unique maximizer.
\end_layout'''

AFRIAT_PREVIEW = r'''\begin_layout Remark
Afriat preview.
 On finite linear-budget data with positive prices and expenditure exhaustion, GARP is equivalent to rationalization by a continuous, strictly increasing, concave utility function.
 Chapter 3 states the exact theorem, writes the Afriat inequalities, and constructs the rationalizing utility
\begin_inset CommandInset citation
LatexCommand citep
key "afriat1967,varian1982"
literal "false"

\end_inset
.
 This is a result about budget geometry and locally nonsatiated utility, not an equivalence with unrestricted selection from the greatest elements of an arbitrary relation.
\end_layout
'''


def rewrite(text: str) -> str:
    if STAMP in text:
        return text

    text = replace_once(text, CH1_OVERVIEW_OLD, CH1_OVERVIEW_NEW, "chapter 1 overview")
    text = replace_section_lead(
        text,
        "Preliminaries",
        "\\begin_layout Standard\n\\begin_inset Note Note\nstatus collapsed\n\n"
        "\\begin_layout Plain Layout\n"
        "ECON803_CONSUMER_RESTRUCTURE_SOURCE:section:basics-of-consumer-theory:02:",
        CH1_LEAD,
    )

    renames = {
        "Preliminaries": "The Benchmark Model",
        "Environment:\n Commodities and Budget Set": "Commodity Space and Budget Sets",
        "The Utility Maximization Problem": "Utility Maximization",
        "KKT Conditions for the UMP": "First-Order and KKT Conditions",
        "Homothetic and Quasilinear Utility Functions": "Workhorse Utility Specifications",
        "Properties of the Indirect Utility Function": "Indirect Utility",
        "Expenditure Minimization Problem (EMP)": "Expenditure Minimization",
        "KKT Conditions for the EMP": "KKT Conditions for Expenditure Minimization",
        "Additional Properties": "Curvature of Hicksian Demand",
        "Summary of Relationships between the EMP and UMP": "Consumer Duality",
        "Summary of the Implications of Utility Maximization": "What Utility Maximization Implies",
        "Demand Functions": "Observed Demand and the Testing Question",
        "Consistency in Consumption": "Walras' Law, Homogeneity, and WARP",
        "Comparative Statics and Slutsky Matrix": "Local Implications of WARP",
        "Generalized Axiom of Revealed Preference (GARP)": "GARP and Afriat's Theorem",
        "Revealed Preference and the Strong Axiom": "SARP and Strict Rationalization",
        "Choice environments": "Choice Environments",
        "Preference relations": "Preference Relations",
        "Revealed choice and WGARP": "Revealed Choice and WGARP",
        "GARP on finite data": "GARP in Abstract Choice and the Budget-Data Specialization",
        "Model and expected utility": "Expected-Utility Representation",
        "Independence Axiom": "Independence",
        "Representation Theorem": "The Finite Expected-Utility Theorem",
        "Recoverability": "Affine Uniqueness and Recoverability",
        "Stochastic dominance on a finite prize set": "First-Order Stochastic Dominance: Finite Support",
        "Revealed Preference of Expected Utility under Concavity": "Revealed Expected Utility under Risk Aversion",
        "Experimental Evidence": "Experimental Evidence on Expected Utility",
        "Expected Utility for Infinite Sets": "Expected Utility on Infinite Outcome Spaces",
        "Stochastic dominance for general distributions": "First-Order Stochastic Dominance: General Distributions",
        "Random utility": "Random Utility on a Fixed Universe",
        "Multinomial logit and IIA": "Multinomial Logit and IIA",
        "Random expected utility": "Random Expected Utility",
        "Attributes and consumer surplus": "Attributes, Choice Probabilities, and Consumer Surplus",
    }
    for old, new in renames.items():
        text = replace_once(
            text,
            f"\\begin_layout Section\n{old}\n\\end_layout",
            f"\\begin_layout Section\n{new}\n\\end_layout",
            f"rename {old}",
        )

    text = replace_once(text, CH4_INTRO_OLD, CH4_INTRO_NEW, "chapter 4 overview")

    chapter_intros = {
        "Question: How do we compute the model's price responses and welfare implications?": CH2_INTRO,
        "Question: Could observed behavior have been generated by the benchmark model, and what can the data identify?": CH3_INTRO,
    }
    for question, intro in chapter_intros.items():
        block = standard(question)
        text = replace_once(text, block, block + intro + "\n", f"intro after {question}")

    # Expected-utility and stochastic-choice chapters have a label layout but
    # no prose bridge. Insert the bridge before the first provenance-free
    # section heading in each chapter.
    for chapter, first_heading, intro in (
        ("Expected Utility and Risk", "Primitives", EU_INTRO),
        (
            "Stochastic Choice and Random Utility",
            "Stochastic Choice on a Finite Universe",
            SC_INTRO,
        ),
    ):
        chapter_at = text.index(f"\\begin_layout Chapter\n{chapter}\n\\end_layout")
        section_at = text.index(
            f"\\begin_layout Section\n{first_heading}\n\\end_layout", chapter_at
        )
        text = text[:section_at] + intro + "\n\n" + text[section_at:]

    # Repair the definition whose inclusion variant made every dataset
    # compatible with universal indifference.
    rationalization_start = "\\begin_layout Definition\nRationalization."
    text = replace_layout_starting(text, rationalization_start, ABSTRACT_RATIONALIZATION)

    # Consolidate the finite-data notation at the start of the Afriat section.
    garp_section = "\\begin_layout Section\nGARP and Afriat's Theorem\n\\end_layout"
    garp_start = text.index(garp_section) + len(garp_section)
    garp_definition = text.index(
        "\\begin_layout Definition\nA finite demand dataset", garp_start
    )
    text = text[:garp_start] + "\n\n" + GARP_LEAD + "\n\n" + text[garp_definition:]

    # Replace the false abstract weak-rationalization equivalence by an honest
    # preview of the budget-specific Afriat theorem already established.
    text = replace_layout_starting(
        text,
        "\\begin_layout Theorem\nFinite-data rationalizability.",
        AFRIAT_PREVIEW,
    )
    text = text.replace(
        "The proof is deferred to the Afriat section of the consumer-theory chapter,",
        "The proof and finite certificate appear in Chapter 3,",
    )
    text = text.replace(
        "In the next chapter,\n prices and wealth impose additional structure,\n and the Afriat inequalities provide a finite certificate that can be checked mechanically.",
        "In Chapter 3, prices and wealth impose the additional linear-budget structure, and the Afriat inequalities provide a finite certificate that can be checked mechanically.",
    )

    # Put a durable non-exported stamp immediately before the next part.
    next_part = "\\begin_layout Part\nRisk, Stochastic Choice, and Attention\n\\end_layout"
    text = replace_once(text, next_part, marker_note(STAMP) + next_part, "polish stamp")
    return text


def main() -> None:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--apply", action="store_true")
    args = parser.parse_args()
    source = BOOK.read_text()
    revised = rewrite(source)
    if args.check:
        if revised != source:
            raise SystemExit("consumer narrative polish is pending")
        print("consumer narrative polish is present")
    elif revised != source:
        BOOK.write_text(revised)
        print(f"updated {BOOK}")
    else:
        print("no changes needed")


if __name__ == "__main__":
    main()
