#!/usr/bin/env python3
"""Rewrite and verify the revealed-preference empirical evidence sections."""

from __future__ import annotations

import argparse
from pathlib import Path


REPO = Path(__file__).resolve().parents[1]
LYX = REPO / "notes" / "Microeconomics_1_notes_by_Victor_Aguiar.lyx"


RESULTS_MARKER = r"""\begin_layout Standard
\begin_inset Note Note
status collapsed

\begin_layout Plain Layout
ECON803_CONSUMER_RESTRUCTURE_SOURCE:section:consumer-theory-utility-maximization:22:results
\end_layout

\end_inset


\end_layout
"""


EXPERIMENT = r"""\begin_layout Section
Experimental Tests of GARP
\end_layout

\begin_layout Standard
Choi,
 Fisman,
 Gale,
 and Kariv study 93 participants recruited from undergraduate classes and staff at the University of California,
 Berkeley.
 Each participant completed 50 portfolio-allocation problems.
 In every problem the participant chose a point on a linear budget over two Arrow securities,
 one paying in each of two states.
 A chosen portfolio can therefore be interpreted as a bundle of state-contingent consumption.
 The 47 participants in the symmetric treatment faced 
\begin_inset Formula $\pi_1=\pi_2=1/2$
\end_inset
;
 the remaining 46 faced 
\begin_inset Formula $\{\pi_1,\pi_2\}=\{1/3,2/3\}$
\end_inset
.
 The computer varied the budget line across rounds,
 and each line may be normalized as 
\begin_inset Formula $p^t\cdot x=1$
\end_inset
.
 Thus participant 
\begin_inset Formula $i$
\end_inset
 generated a panel 
\begin_inset Formula $\mathcal O_i=\{(p_i^t,x_i^t)\}_{t=1}^{50}$
\end_inset
 to which GARP can be applied
\begin_inset CommandInset citation
LatexCommand citep
key "choifismangalekariv2007"
literal "false"

\end_inset
.
\end_layout

""" + RESULTS_MARKER + r"""
\begin_layout Standard
The exact-GARP tabulation in
\begin_inset CommandInset citation
LatexCommand citep
key "polissonquahrenou2020"
literal "false"

\end_inset
 reports that 12 of 47 participants in the symmetric treatment and 4 of 46 in the asymmetric treatment satisfy GARP.
 Overall,
 16 of 93 participants---approximately 17 percent---pass the exact test.
 The interpretation is precise but limited: a recorded panel that fails cannot be rationalized exactly by one locally nonsatiated utility function under the maintained budget data.
 The result alone does not distinguish preference instability from optimization error,
 recording error,
 or price misperception.
 Nor does a binary pass rate measure the economic magnitude of a violation: one strict revealed-preference cycle is sufficient for rejection.
 The critical cost-efficiency index introduced next provides a graded measure,
 while a random-choice benchmark helps assess the power of the design.
\end_layout

"""


MEASUREMENT = r"""\begin_layout Section
Measurement Error and Statistical Revealed Preference
\end_layout

\begin_layout Standard
Ahn,
 Choi,
 Gale,
 and Kariv collect 50 portfolio choices from each of 154 participants.
 The assets are three Arrow securities corresponding to three states: one state has a known probability,
 whereas the other two states are ambiguous.
 This is a three-state contingent-consumption experiment,
 not an ordinary three-good demand experiment.
 Applied directly to the recorded choices and budgets,
 the deterministic GARP test is passed by 12.99 percent of participants
\begin_inset CommandInset citation
LatexCommand citep
key "ahnchoigalekariv2014,aguiarkashaev2021"
literal "false"

\end_inset
.
\end_layout

\begin_layout Standard
A deterministic revealed-preference test treats recorded prices and choices as the economically relevant data.
 Aguiar and Kashaev instead ask whether the population distribution of recorded panels can be generated by latent utility-maximizing behavior together with a disciplined measurement process
\begin_inset CommandInset citation
LatexCommand citep
key "aguiarkashaev2021"
literal "false"

\end_inset
.
 For participant 
\begin_inset Formula $i$
\end_inset
 and task 
\begin_inset Formula $t$
\end_inset
,
 let 
\begin_inset Formula $(p_i^t,x_i^t)$
\end_inset
 denote the recorded pair and 
\begin_inset Formula $(p_i^{*t},x_i^{*t})$
\end_inset
 the latent pair entering the maintained optimizing model.
 An additive relation such as 
\begin_inset Formula $x_i^t=x_i^{*t}+\varepsilon_{x,i}^t$
\end_inset
 or 
\begin_inset Formula $p_i^t=p_i^{*t}+\varepsilon_{p,i}^t$
\end_inset
 is a schematic illustration,
 not the identifying content of the framework.
 Empirical content comes from restrictions linking observed and latent variables---especially population centering conditions---combined with utility-maximization restrictions.
 If both latent data and measurement error are unrestricted,
 observed violations can be rationalized too freely for the exercise to be informative.
\end_layout

\begin_layout Standard
In their application,
 Aguiar and Kashaev study two measurement channels separately.
 Under the price-misperception specification,
 recorded choices are exact and perceived prices may differ from displayed prices,
 subject to agreement between perceived and displayed price vectors on average for each task.
 Under the trembling-hand specification,
 displayed prices are exact and chosen allocations may contain mean-zero error.
 The validation evidence is asymmetric: the paper reports direct evidence for the centering condition on hand errors,
 whereas the evidence for price misperception is indirect and tied to the graphical design.
\end_layout

\begin_layout Standard
The empirical comparison is therefore conditional.
 At the 5 percent significance level,
 the authors do not reject the joint null of static utility maximization and mean-centered price misperception.
 They strongly reject the joint null when the only discrepancy is a centered trembling-hand error in consumption.
 The data thus favor the price-misperception specification over that particular consumption-error specification.
 They do not establish that every participant is deterministically GARP-consistent,
 that price misperception is the unique source of every violation,
 or that utility maximization has been confirmed.
 Failure to reject is evidence about a joint model of preferences and measurement,
 not proof of rationality.
\end_layout

"""


OLD_FIGURE_CAPTION = r"""Revealed-preference choices of Subject 216 in the symmetric treatment.
 Gray lines are observed budgets,
 black dots are chosen bundles,
 and the dashed line is the 45-degree line.
 Coordinates recovered from Quah's survey slides;
 underlying experiment:

\begin_inset space ~
\end_inset

\begin_inset CommandInset citation
LatexCommand citep
key "quah2015survey,choifismangalekariv2007"
literal "false"

\end_inset
."""


NEW_FIGURE_CAPTION = r"""Observed portfolio choices of Subject 216 in the symmetric treatment.
 Gray lines are budget lines,
 black points are chosen portfolios,
 and the dashed 45-degree line marks equal consumption in the two states.
 Redrawn from Quah's survey using the experiment of
\begin_inset CommandInset citation
LatexCommand citep
key "quah2015survey,choifismangalekariv2007"
literal "false"

\end_inset
."""


OLD_CCEI_CAPTION = r"""Share of observations whose CCEI is at least
\begin_inset space ~
\end_inset

\begin_inset Formula $\alpha$
\end_inset

:
 observed GARP compliance and Quah's simulated GARP benchmark.
 Curves recovered from Quah's survey slides (slide 27)
\begin_inset space ~
\end_inset

\begin_inset CommandInset citation
LatexCommand citep
key "quah2015survey"
literal "false"

\end_inset
."""


NEW_CCEI_CAPTION = r"""Survival functions 
\begin_inset Formula $\alpha\mapsto\Pr\{\operatorname{CCEI}_i\geq\alpha\}$
\end_inset
 for the experimental participants and for Bronars-style simulated participants who choose uniformly on each budget line.
 Redrawn from Quah's survey;
 experiment and simulation design from Choi et al.,
 with subsequent tabulation in Polisson,
 Quah,
 and Renou
\begin_inset CommandInset citation
LatexCommand citep
key "quah2015survey,choifismangalekariv2007,polissonquahrenou2020"
literal "false"

\end_inset
."""


FORBIDDEN = (
    "Experiments about Testing Rationality",
    "93 undergraduate subjects",
    "Share of observations whose CCEI",
    "using 3 goods instead of 2",
    "Aguiar and Kashaev (2020",
    "misperception of prices seems to be the culprit",
    "Does this confirm rationality?",
)


def replace_region(source: str, headings: tuple[str, ...], end: str, body: str) -> str:
    positions = [source.find(h) for h in headings]
    positions = [p for p in positions if p >= 0]
    if not positions:
        raise SystemExit(f"cannot locate any section heading: {headings}")
    start = min(positions)
    stop = source.index(end, start)
    return source[:start] + body + source[stop:]


def rewrite(source: str) -> str:
    source = replace_region(
        source,
        (
            "\\begin_layout Section\nExperiments about Testing Rationality\n",
            "\\begin_layout Section\nExperimental Tests of GARP\n",
        ),
        "\\begin_layout Standard\n\\begin_inset Float figure\n",
        EXPERIMENT,
    )
    source = source.replace(OLD_FIGURE_CAPTION, NEW_FIGURE_CAPTION)
    source = source.replace(
        "\\begin_layout Section\nAfriat's Cost-Efficiency Index\n",
        "\\begin_layout Section\nThe Critical Cost-Efficiency Index\n",
    )
    source = source.replace(
        " A value of one means that the original data satisfy GARP; a smaller value is the largest common fraction of observed expenditure that can be retained while eliminating every GARP violation.",
        " A value of one means that the original data satisfy GARP; a smaller value is the largest efficiency level at which the adjusted revealed-preference test remains free of GARP violations.  This is an expenditure-efficiency normalization, not a claim that the recorded bundle was literally purchased after discarding the remaining expenditure.",
    )
    source = source.replace(OLD_CCEI_CAPTION, NEW_CCEI_CAPTION)

    measurement_marker = (
        "\\begin_layout Plain Layout\n"
        "ECON803_CONSUMER_RESTRUCTURE_SOURCE:section:consumer-theory-utility-maximization:27:problems"
    )
    marker_at = source.index(measurement_marker)
    stop = source.rfind("\\begin_layout Standard\n", 0, marker_at)
    source = replace_region(
        source,
        (
            "\\begin_layout Section\nMeasurement Error\n",
            "\\begin_layout Section\nMeasurement Error and Statistical Revealed Preference\n",
        ),
        source[stop:marker_at],
        MEASUREMENT,
    )
    return source


def validate(source: str) -> None:
    required = (
        "Experimental Tests of GARP",
        "polissonquahrenou2020",
        "Observed portfolio choices of Subject 216",
        "Bronars-style simulated participants",
        "Measurement Error and Statistical Revealed Preference",
        "ahnchoigalekariv2014,aguiarkashaev2021",
        "Failure to reject is evidence about a joint model",
    )
    missing = [item for item in required if item not in source]
    lingering = [item for item in FORBIDDEN if item in source]
    if missing:
        raise SystemExit("empirical polish missing: " + ", ".join(missing))
    if lingering:
        raise SystemExit("superseded empirical prose remains: " + ", ".join(lingering))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.apply == args.check:
        parser.error("choose exactly one of --apply or --check")
    source = LYX.read_text(encoding="utf-8")
    if args.apply:
        updated = rewrite(source)
        validate(updated)
        LYX.write_text(updated, encoding="utf-8")
        print("Applied verified empirical-evidence rewrite.")
    else:
        validate(source)
        print("PASS: empirical-evidence rewrite is present.")


if __name__ == "__main__":
    main()
